[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Difference Calculator"
authors = ["Nadia St"]
license = "none"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gendiff = "hexlet_code.scripts.gendiff:main"

