name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Убедитесь, что используете правильную версию Python

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with poetry
        run: |
          poetry install --no-dev

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/hexlet_code" >> $GITHUB_ENV  # Устанавливаем PYTHONPATH

      - name: Run tests
        run: |
          poetry run pytest -vv --exitfirst

